In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import pickle

In [4]:
df = pd.read_csv("train.csv")

In [5]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL           65     8450   Pave     0      Reg   
1   2          20       RL           80     9600   Pave     0      Reg   
2   3          60       RL           68    11250   Pave     0      IR1   
3   4          70       RL           60     9550   Pave     0      IR1   
4   5          60       RL           84    14260   Pave     0      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0      0     0           0       0      2   
1         Lvl    AllPub  ...        0      0     0           0       0      5   
2         Lvl    AllPub  ...        0      0     0           0       0      9   
3         Lvl    AllPub  ...        0      0     0           0       0      2   
4         Lvl    AllPub  ...        0      0     0           0       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [6]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [7]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [8]:
df_target = df[['SalePrice']]

In [9]:
df_ = df.drop(['SalePrice'], axis = 1)

In [10]:
df_target.isnull().sum()

SalePrice    0
dtype: int64

In [11]:
df_.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 80, dtype: int64

In [12]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [13]:
np.unique(df['MSSubClass'],return_counts = True)

(array([ 20,  30,  40,  45,  50,  60,  70,  75,  80,  85,  90, 120, 160,
        180, 190]),
 array([536,  69,   4,  12, 144, 299,  60,  16,  58,  20,  52,  87,  63,
         10,  30]))

In [14]:
np.unique(df['MSZoning'],return_counts = True)

(array(['C (all)', 'FV', 'RH', 'RL', 'RM'], dtype=object),
 array([  10,   65,   16, 1151,  218]))

In [92]:
df_menu = df_

In [ ]:
df_MSZoning = pd.get_dummies(df['MSZoning'], dummy_na=True)

In [15]:
np.unique(df['LotFrontage'],return_counts = True)

(array([  0,  21,  24,  30,  32,  33,  34,  35,  36,  37,  38,  39,  40,
         41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111, 112, 114, 115, 116, 118, 120, 121,
        122, 124, 128, 129, 130, 134, 137, 138, 140, 141, 144, 149, 150,
        152, 153, 160, 168, 174, 182, 313]),
 array([259,  23,  19,   6,   5,   1,  10,   9,   6,   5,   1,   1,  12,
          6,   4,  12,   9,   3,   1,   5,   6,   4,  57,  15,  14,  10,
          6,  17,   5,  12,   7,  13, 143,   8,   9,  17,  19,  44,  15,
         12,  19,  11,  70,  12,  17,  18,  15,  53,  11,   9,  25,  17,
         69,   6,  12,   5,   9,  40,  10,   5,  10,   6,  23,   6,  10,
      

In [16]:
np.unique(df['LotArea'],return_counts = True)

(array([  1300,   1477,   1491, ..., 159000, 164660, 215245]),
 array([1, 1, 1, ..., 1, 1, 1]))

In [17]:
np.unique(df['Street'],return_counts = True)

(array(['Grvl', 'Pave'], dtype=object), array([   6, 1454]))

In [18]:
np.unique(df['Alley'],return_counts = True)

(array(['0', 'Grvl', 'Pave'], dtype=object), array([1369,   50,   41]))

In [19]:
np.unique(df['LotShape'],return_counts = True)

(array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object),
 array([484,  41,  10, 925]))

In [20]:
np.unique(df['LandContour'],return_counts = True)

(array(['Bnk', 'HLS', 'Low', 'Lvl'], dtype=object),
 array([  63,   50,   36, 1311]))

In [21]:
np.unique(df['Utilities'],return_counts = True)

(array(['AllPub', 'NoSeWa'], dtype=object), array([1459,    1]))

In [22]:
np.unique(df['LotConfig'],return_counts = True)

(array(['Corner', 'CulDSac', 'FR2', 'FR3', 'Inside'], dtype=object),
 array([ 263,   94,   47,    4, 1052]))

In [23]:
np.unique(df['LandSlope'],return_counts = True)

(array(['Gtl', 'Mod', 'Sev'], dtype=object), array([1382,   65,   13]))

In [24]:
np.unique(df['Condition1'],return_counts = True)

(array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNe',
        'RRNn'], dtype=object),
 array([  48,   81, 1260,    8,   19,   11,   26,    2,    5]))

In [25]:
np.unique(df['Condition2'],return_counts = True)

(array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNn'],
       dtype=object),
 array([   2,    6, 1445,    1,    2,    1,    1,    2]))

In [26]:
np.unique(df['BldgType'],return_counts = True)

(array(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE'], dtype=object),
 array([1220,   31,   52,   43,  114]))

In [27]:
np.unique(df['HouseStyle'],return_counts = True)

(array(['1.5Fin', '1.5Unf', '1Story', '2.5Fin', '2.5Unf', '2Story',
        'SFoyer', 'SLvl'], dtype=object),
 array([154,  14, 726,   8,  11, 445,  37,  65]))

In [28]:
np.unique(df['OverallQual'],return_counts = True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([  2,   3,  20, 116, 397, 374, 319, 168,  43,  18]))

In [29]:
np.unique(df['OverallCond'],return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([  1,   5,  25,  57, 821, 252, 205,  72,  22]))

In [30]:
np.unique(df['YearBuilt'],return_counts = True)

(array([1872, 1875, 1880, 1882, 1885, 1890, 1892, 1893, 1898, 1900, 1904,
        1905, 1906, 1908, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
        1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
        1929, 1930, 1931, 1932, 1934, 1935, 1936, 1937, 1938, 1939, 1940,
        1941, 1942, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953,
        1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964,
        1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
        1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
        1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
        1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
        2009, 2010]),
 array([ 1,  1,  4,  1,  2,  2,  2,  1,  1, 10,  1,  1,  1,  2, 17,  1,  3,
         1,  7, 10,  8,  1,  7,  3, 30,  6,  8,  7,  7, 16,  9,  3,  7,  4,
         9,  6,  4,  3,  6,  9,  5,  4,  8, 18, 15,  2,  6,  7,  5, 14, 12,
        20

In [31]:
np.unique(df['YearRemodAdd'],return_counts = True)

(array([1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
        1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
        1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
        1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
        1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
        2005, 2006, 2007, 2008, 2009, 2010]),
 array([178,   4,   5,  10,  14,   9,  10,   9,  15,  18,  12,   8,  14,
         13,  11,  19,  15,  12,  17,  14,  26,  18,  20,  11,   7,  10,
         30,  25,  16,  10,  12,   8,   7,   5,   7,   9,   5,  10,   9,
         11,  15,  14,  17,  19,  22,  31,  36,  25,  36,  30,  55,  21,
         48,  51,  62,  73,  97,  76,  40,  23,   6]))

In [32]:
np.unique(df['RoofStyle'],return_counts = True)

(array(['Flat', 'Gable', 'Gambrel', 'Hip', 'Mansard', 'Shed'], dtype=object),
 array([  13, 1141,   11,  286,    7,    2]))

In [33]:
np.unique(df['RoofMatl'],return_counts = True)

(array(['ClyTile', 'CompShg', 'Membran', 'Metal', 'Roll', 'Tar&Grv',
        'WdShake', 'WdShngl'], dtype=object),
 array([   1, 1434,    1,    1,    1,   11,    5,    6]))

In [34]:
np.unique(df['Exterior1st'],return_counts = True)

(array(['AsbShng', 'AsphShn', 'BrkComm', 'BrkFace', 'CBlock', 'CemntBd',
        'HdBoard', 'ImStucc', 'MetalSd', 'Plywood', 'Stone', 'Stucco',
        'VinylSd', 'Wd Sdng', 'WdShing'], dtype=object),
 array([ 20,   1,   2,  50,   1,  61, 222,   1, 220, 108,   2,  25, 515,
        206,  26]))

In [35]:
np.unique(df['Exterior2nd'],return_counts = True)

(array(['AsbShng', 'AsphShn', 'Brk Cmn', 'BrkFace', 'CBlock', 'CmentBd',
        'HdBoard', 'ImStucc', 'MetalSd', 'Other', 'Plywood', 'Stone',
        'Stucco', 'VinylSd', 'Wd Sdng', 'Wd Shng'], dtype=object),
 array([ 20,   3,   7,  25,   1,  60, 207,  10, 214,   1, 142,   5,  26,
        504, 197,  38]))

In [36]:
np.unique(df['MasVnrType'],return_counts = True)

(array(['0', 'BrkCmn', 'BrkFace', 'None', 'Stone'], dtype=object),
 array([  8,  15, 445, 864, 128]))

In [37]:
np.unique(df['MasVnrArea'],return_counts = True)

(array([   0,    1,   11,   14,   16,   18,   22,   24,   27,   28,   30,
          31,   32,   34,   36,   38,   40,   41,   42,   44,   45,   46,
          48,   50,   51,   53,   54,   56,   57,   60,   63,   64,   65,
          66,   67,   68,   70,   72,   74,   75,   76,   80,   81,   82,
          84,   85,   86,   88,   89,   90,   92,   94,   95,   96,   97,
          98,   99,  100,  101,  102,  104,  105,  106,  108,  109,  110,
         112,  113,  114,  115,  116,  117,  119,  120,  122,  123,  125,
         126,  127,  128,  130,  132,  135,  136,  137,  138,  140,  142,
         143,  144,  145,  146,  147,  148,  149,  150,  151,  153,  154,
         156,  157,  158,  160,  161,  162,  163,  164,  165,  166,  167,
         168,  169,  170,  171,  172,  174,  175,  176,  178,  180,  182,
         183,  184,  186,  188,  189,  192,  194,  196,  200,  202,  203,
         204,  205,  206,  207,  208,  209,  210,  212,  215,  216,  218,
         219,  220,  223,  224,  225, 

In [38]:
np.unique(df['ExterQual'],return_counts = True)

(array(['Ex', 'Fa', 'Gd', 'TA'], dtype=object), array([ 52,  14, 488, 906]))

In [39]:
np.unique(df['ExterCond'],return_counts = True)

(array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([   3,   28,  146,    1, 1282]))

In [40]:
np.unique(df['Foundation'],return_counts = True)

(array(['BrkTil', 'CBlock', 'PConc', 'Slab', 'Stone', 'Wood'], dtype=object),
 array([146, 634, 647,  24,   6,   3]))

In [41]:
np.unique(df['BsmtQual'],return_counts = True)

(array(['0', 'Ex', 'Fa', 'Gd', 'TA'], dtype=object),
 array([ 37, 121,  35, 618, 649]))

In [42]:
np.unique(df['BsmtCond'],return_counts = True)

(array(['0', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([  37,   45,   65,    2, 1311]))

In [43]:
np.unique(df['BsmtExposure'],return_counts = True)

(array(['0', 'Av', 'Gd', 'Mn', 'No'], dtype=object),
 array([ 38, 221, 134, 114, 953]))

In [44]:
np.unique(df['BsmtFinType1'],return_counts = True)

(array(['0', 'ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf'], dtype=object),
 array([ 37, 220, 148, 418,  74, 133, 430]))

In [45]:
np.unique(df['BsmtFinSF1'],return_counts = True)

(array([   0,    2,   16,   20,   24,   25,   27,   28,   33,   35,   36,
          40,   41,   48,   49,   50,   56,   57,   63,   64,   72,   75,
          80,   81,   94,  104,  108,  111,  116,  120,  125,  129,  131,
         133,  138,  141,  144,  150,  152,  156,  162,  165,  167,  168,
         170,  176,  179,  180,  182,  185,  187,  188,  189,  191,  192,
         193,  194,  196,  197,  203,  204,  206,  209,  210,  212,  213,
         216,  218,  219,  220,  222,  223,  224,  226,  228,  231,  234,
         236,  239,  240,  241,  247,  248,  249,  250,  251,  252,  256,
         257,  259,  262,  264,  266,  270,  273,  275,  280,  281,  282,
         284,  285,  288,  290,  292,  294,  296,  297,  298,  299,  300,
         301,  306,  308,  309,  310,  311,  312,  315,  317,  319,  320,
         321,  322,  324,  326,  328,  329,  330,  331,  334,  336,  338,
         340,  341,  344,  348,  349,  350,  351,  352,  353,  354,  356,
         358,  360,  361,  364,  365, 

In [46]:
np.unique(df['BsmtFinType2'],return_counts = True)

(array(['0', 'ALQ', 'BLQ', 'GLQ', 'LwQ', 'Rec', 'Unf'], dtype=object),
 array([  38,   19,   33,   14,   46,   54, 1256]))

In [47]:
np.unique(df['BsmtFinSF2'],return_counts = True)

(array([   0,   28,   32,   35,   40,   41,   64,   68,   80,   81,   93,
          96,  105,  106,  108,  110,  117,  119,  121,  123,  125,  127,
         128,  132,  139,  144,  147,  149,  150,  163,  165,  168,  169,
         173,  174,  175,  177,  180,  181,  182,  184,  193,  202,  208,
         210,  211,  215,  219,  228,  230,  232,  239,  240,  258,  264,
         273,  276,  279,  287,  290,  294,  306,  311,  324,  334,  336,
         344,  345,  352,  354,  362,  374,  375,  377,  380,  391,  396,
         400,  411,  420,  435,  438,  441,  465,  466,  468,  469,  472,
         479,  480,  486,  491,  492,  495,  499,  500,  506,  531,  532,
         539,  544,  546,  547,  551,  557,  580,  600,  606,  608,  612,
         620,  627,  630,  634,  645,  661,  668,  670,  682,  690,  692,
         712,  713,  723,  764,  768,  791,  820,  823,  841,  869,  872,
         906,  972, 1029, 1031, 1057, 1061, 1063, 1080, 1085, 1120, 1127,
        1474]),
 array([1293,    1,   

In [48]:
np.unique(df['BsmtUnfSF'],return_counts = True)

(array([   0,   14,   15,   23,   26,   29,   30,   32,   35,   36,   38,
          39,   40,   50,   55,   60,   61,   64,   70,   72,   74,   75,
          76,   77,   78,   80,   81,   82,   83,   84,   88,   89,   90,
          92,   93,   95,   96,   99,  100,  102,  103,  104,  105,  107,
         108,  110,  111,  112,  113,  114,  115,  117,  119,  120,  121,
         122,  124,  125,  126,  130,  131,  132,  133,  134,  135,  136,
         138,  140,  141,  142,  143,  148,  149,  150,  151,  153,  154,
         155,  156,  160,  161,  162,  163,  165,  166,  167,  168,  169,
         170,  171,  172,  173,  174,  175,  176,  177,  178,  179,  180,
         184,  186,  187,  188,  189,  190,  191,  192,  193,  195,  196,
         197,  198,  200,  201,  203,  204,  207,  208,  210,  212,  216,
         217,  218,  219,  220,  221,  223,  224,  225,  227,  229,  230,
         234,  235,  237,  238,  239,  240,  241,  242,  244,  245,  246,
         247,  248,  250,  251,  252, 

In [49]:
np.unique(df['TotalBsmtSF'],return_counts = True)

(array([   0,  105,  190,  264,  270,  290,  319,  360,  372,  384,  408,
         420,  440,  458,  462,  480,  482,  483,  485,  504,  506,  520,
         525,  528,  530,  533,  536,  539,  540,  544,  546,  547,  551,
         559,  560,  561,  570,  572,  576,  585,  588,  596,  600,  602,
         608,  611,  612,  616,  617,  622,  624,  625,  626,  630,  636,
         637,  641,  644,  648,  649,  650,  651,  654,  655,  656,  658,
         660,  661,  662,  663,  672,  673,  676,  680,  683,  684,  686,
         689,  690,  691,  693,  696,  697,  698,  700,  702,  704,  707,
         708,  709,  710,  712,  713,  714,  715,  716,  718,  720,  721,
         723,  725,  727,  728,  729,  731,  732,  735,  736,  738,  740,
         741,  742,  744,  746,  747,  750,  755,  756,  757,  761,  764,
         765,  768,  770,  771,  773,  774,  776,  777,  778,  780,  783,
         784,  788,  789,  791,  792,  793,  794,  795,  796,  798,  799,
         800,  802,  803,  804,  806, 

In [50]:
np.unique(df['Heating'],return_counts = True)

(array(['Floor', 'GasA', 'GasW', 'Grav', 'OthW', 'Wall'], dtype=object),
 array([   1, 1428,   18,    7,    2,    4]))

In [51]:
np.unique(df['HeatingQC'],return_counts = True)

(array(['Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([741,  49, 241,   1, 428]))

In [52]:
np.unique(df['CentralAir'],return_counts = True)

(array(['N', 'Y'], dtype=object), array([  95, 1365]))

In [53]:
np.unique(df['Electrical'],return_counts = True)

(array(['0', 'FuseA', 'FuseF', 'FuseP', 'Mix', 'SBrkr'], dtype=object),
 array([   1,   94,   27,    3,    1, 1334]))

In [54]:
np.unique(df['1stFlrSF'],return_counts = True)

(array([ 334,  372,  438,  480,  483,  495,  520,  525,  526,  536,  546,
         551,  561,  572,  575,  576,  581,  596,  600,  605,  612,  616,
         624,  625,  626,  630,  649,  658,  660,  661,  663,  664,  672,
         673,  676,  679,  680,  682,  684,  686,  689,  691,  693,  694,
         696,  697,  698,  702,  703,  707,  708,  713,  716,  720,  725,
         728,  729,  734,  735,  736,  738,  741,  742,  747,  750,  751,
         752,  753,  754,  755,  756,  757,  760,  764,  765,  767,  768,
         769,  770,  772,  773,  774,  778,  779,  780,  783,  784,  786,
         788,  789,  790,  792,  793,  794,  796,  798,  799,  800,  802,
         803,  804,  806,  807,  808,  810,  811,  812,  813,  814,  815,
         816,  818,  820,  822,  824,  825,  827,  829,  831,  832,  833,
         835,  838,  840,  841,  842,  845,  846,  847,  848,  849,  851,
         854,  855,  856,  858,  859,  860,  861,  864,  865,  866,  869,
         872,  874,  875,  876,  877, 

In [55]:
np.unique(df['2ndFlrSF'],return_counts = True)

(array([   0,  110,  167,  192,  208,  213,  220,  224,  240,  252,  272,
         299,  304,  316,  319,  325,  332,  336,  348,  349,  351,  358,
         368,  370,  371,  378,  384,  390,  403,  406,  408,  430,  432,
         438,  439,  441,  445,  448,  454,  455,  456,  457,  462,  464,
         467,  468,  472,  473,  475,  482,  495,  504,  510,  511,  512,
         514,  517,  518,  520,  521,  523,  524,  526,  527,  530,  533,
         534,  539,  540,  545,  546,  547,  548,  550,  551,  556,  557,
         560,  561,  564,  566,  567,  568,  571,  573,  574,  576,  580,
         581,  582,  584,  586,  587,  589,  590,  591,  592,  595,  596,
         600,  601,  602,  605,  611,  612,  620,  622,  623,  625,  626,
         628,  630,  631,  634,  636,  639,  640,  644,  648,  649,  650,
         651,  653,  656,  660,  661,  664,  665,  668,  670,  672,  676,
         677,  678,  679,  682,  684,  685,  686,  687,  688,  689,  691,
         694,  695,  698,  700,  701, 

In [56]:
np.unique(df['LowQualFinSF'],return_counts = True)

(array([  0,  53,  80, 120, 144, 156, 205, 232, 234, 360, 371, 384, 390,
        392, 397, 420, 473, 479, 481, 513, 514, 515, 528, 572]),
 array([1434,    1,    3,    1,    1,    1,    1,    1,    1,    2,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1]))

In [57]:
np.unique(df['GrLivArea'],return_counts = True)

(array([ 334,  438,  480,  520,  605,  616,  630,  672,  691,  693,  694,
         698,  708,  720,  729,  747,  752,  754,  764,  767,  768,  773,
         774,  778,  780,  784,  788,  789,  790,  792,  796,  800,  803,
         804,  813,  816,  825,  827,  832,  833,  835,  838,  840,  841,
         845,  848,  854,  858,  860,  861,  864,  866,  869,  872,  874,
         875,  882,  884,  886,  892,  893,  894,  899,  900,  901,  902,
         904,  907,  910,  912,  913,  914,  918,  923,  924,  925,  928,
         930,  932,  935,  936,  938,  943,  944,  948,  950,  951,  952,
         954,  955,  958,  960,  964,  965,  968,  969,  970,  971,  972,
         974,  980,  981,  985,  986,  987,  988,  990,  996,  999, 1002,
        1003, 1004, 1005, 1006, 1008, 1012, 1015, 1020, 1022, 1026, 1028,
        1029, 1032, 1034, 1039, 1040, 1041, 1044, 1047, 1048, 1050, 1052,
        1053, 1054, 1056, 1057, 1060, 1062, 1063, 1065, 1067, 1068, 1069,
        1072, 1073, 1074, 1077, 1078, 

In [58]:
np.unique(df['BsmtFullBath'],return_counts = True)

(array([0, 1, 2, 3]), array([856, 588,  15,   1]))

In [59]:
np.unique(df['BsmtHalfBath'],return_counts = True)

(array([0, 1, 2]), array([1378,   80,    2]))

In [60]:
np.unique(df['FullBath'],return_counts = True)

(array([0, 1, 2, 3]), array([  9, 650, 768,  33]))

In [61]:
np.unique(df['HalfBath'],return_counts = True)

(array([0, 1, 2]), array([913, 535,  12]))

In [62]:
np.unique(df['BedroomAbvGr'],return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 8]),
 array([  6,  50, 358, 804, 213,  21,   7,   1]))

In [63]:
np.unique(df['KitchenQual'],return_counts = True)

(array(['Ex', 'Fa', 'Gd', 'TA'], dtype=object), array([100,  39, 586, 735]))

In [64]:
np.unique(df['TotRmsAbvGrd'],return_counts = True)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14]),
 array([  1,  17,  97, 275, 402, 329, 187,  75,  47,  18,  11,   1]))

In [65]:
np.unique(df['Functional'],return_counts = True)

(array(['Maj1', 'Maj2', 'Min1', 'Min2', 'Mod', 'Sev', 'Typ'], dtype=object),
 array([  14,    5,   31,   34,   15,    1, 1360]))

In [66]:
np.unique(df['Fireplaces'],return_counts = True)

(array([0, 1, 2, 3]), array([690, 650, 115,   5]))

In [67]:
np.unique(df['FireplaceQu'],return_counts = True)

(array(['0', 'Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([690,  24,  33, 380,  20, 313]))

In [68]:
np.unique(df['GarageType'],return_counts = True)

(array(['0', '2Types', 'Attchd', 'Basment', 'BuiltIn', 'CarPort', 'Detchd'],
       dtype=object),
 array([ 81,   6, 870,  19,  88,   9, 387]))

In [69]:
np.unique(df['GarageYrBlt'],return_counts = True)

(array([   0, 1900, 1906, 1908, 1910, 1914, 1915, 1916, 1918, 1920, 1921,
        1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
        1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1945,
        1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956,
        1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967,
        1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978,
        1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989,
        1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
        2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010]),
 array([81,  1,  1,  1,  3,  2,  2,  5,  2, 14,  3,  5,  3,  3, 10,  6,  1,
         4,  2,  8,  4,  3,  1,  2,  4,  5,  2,  3,  9, 14, 10,  2,  4,  4,
         2, 11,  8, 24,  6,  3, 12, 19, 13, 16, 20, 21, 17, 19, 13, 21, 16,
        18, 21, 21, 15, 26, 15, 20, 13, 14, 14, 18,  9, 29, 35, 19, 15, 15,
        10,  4,  7,  8, 10,  6, 11

In [70]:
np.unique(df['GarageFinish'],return_counts = True)

(array(['0', 'Fin', 'RFn', 'Unf'], dtype=object), array([ 81, 352, 422, 605]))

In [71]:
np.unique(df['GarageCars'],return_counts = True)

(array([0, 1, 2, 3, 4]), array([ 81, 369, 824, 181,   5]))

In [72]:
np.unique(df['GarageArea'],return_counts = True)

(array([   0,  160,  164,  180,  186,  189,  192,  198,  200,  205,  208,
         210,  213,  216,  220,  225,  228,  230,  234,  240,  244,  246,
         248,  250,  252,  254,  255,  256,  260,  261,  264,  270,  271,
         273,  275,  276,  280,  281,  282,  283,  284,  286,  287,  288,
         290,  292,  294,  296,  297,  299,  300,  301,  303,  304,  305,
         306,  308,  309,  312,  315,  318,  319,  320,  322,  324,  325,
         326,  327,  328,  330,  336,  338,  342,  343,  349,  350,  352,
         354,  358,  360,  364,  366,  367,  368,  370,  372,  373,  375,
         377,  379,  380,  384,  386,  388,  389,  390,  392,  393,  396,
         397,  398,  400,  402,  403,  404,  405,  406,  408,  409,  410,
         412,  413,  414,  416,  418,  420,  422,  423,  424,  425,  426,
         427,  429,  430,  431,  432,  433,  434,  435,  436,  437,  438,
         439,  440,  441,  442,  444,  445,  447,  450,  451,  452,  453,
         454,  455,  456,  457,  458, 

In [73]:
np.unique(df['GarageQual'],return_counts = True)

(array(['0', 'Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([  81,    3,   48,   14,    3, 1311]))

In [74]:
np.unique(df['GarageCond'],return_counts = True)

(array(['0', 'Ex', 'Fa', 'Gd', 'Po', 'TA'], dtype=object),
 array([  81,    2,   35,    9,    7, 1326]))

In [75]:
np.unique(df['PavedDrive'],return_counts = True)

(array(['N', 'P', 'Y'], dtype=object), array([  90,   30, 1340]))

In [76]:
np.unique(df['WoodDeckSF'],return_counts = True)

(array([  0,  12,  24,  26,  28,  30,  32,  33,  35,  36,  38,  40,  42,
         44,  45,  48,  49,  52,  53,  55,  56,  57,  58,  60,  63,  64,
         66,  68,  70,  72,  74,  78,  80,  81,  84,  85,  86,  87,  88,
         89,  90,  92,  95,  96,  97,  98, 100, 103, 104, 105, 106, 108,
        110, 112, 113, 114, 115, 116, 117, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 132, 133, 135, 136, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 153, 154, 155, 156, 158, 159,
        160, 161, 162, 164, 165, 166, 168, 169, 170, 171, 172, 173, 175,
        176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        190, 192, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 206,
        207, 208, 209, 210, 212, 214, 215, 216, 218, 219, 220, 222, 224,
        227, 228, 229, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 245, 248, 250, 252, 253, 255, 256, 257, 260, 261, 262,
        263, 264, 265, 268, 269, 270, 272, 276, 278

In [77]:
np.unique(df['OpenPorchSF'],return_counts = True)

(array([  0,   4,   8,  10,  11,  12,  15,  16,  17,  18,  20,  21,  22,
         23,  24,  25,  26,  27,  28,  29,  30,  32,  33,  34,  35,  36,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  72,  73,  74,  75,  76,  77,
         78,  80,  81,  82,  83,  84,  85,  86,  87,  88,  90,  91,  92,
         93,  94,  95,  96,  98,  99, 100, 101, 102, 103, 104, 105, 106,
        108, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 122,
        123, 124, 125, 126, 128, 129, 130, 131, 132, 133, 134, 135, 136,
        137, 138, 140, 141, 142, 144, 146, 148, 150, 151, 152, 154, 155,
        156, 158, 159, 160, 162, 166, 168, 169, 170, 172, 174, 175, 176,
        180, 182, 184, 185, 187, 188, 189, 191, 192, 195, 198, 199, 200,
        204, 205, 207, 208, 210, 211, 213, 214, 224, 228, 229, 231, 234,
        235, 236, 238, 240, 241, 243, 244, 247, 250

In [78]:
np.unique(df['EnclosedPorch'],return_counts = True)

(array([  0,  19,  20,  24,  30,  32,  34,  36,  37,  39,  40,  42,  44,
         48,  50,  52,  54,  56,  60,  64,  67,  68,  70,  77,  80,  81,
         84,  87,  90,  91,  94,  96,  98,  99, 100, 102, 105, 108, 112,
        114, 115, 116, 120, 123, 126, 128, 129, 130, 134, 136, 137, 138,
        140, 143, 144, 145, 148, 150, 154, 156, 158, 160, 162, 164, 168,
        169, 170, 172, 174, 176, 177, 180, 183, 184, 185, 189, 190, 192,
        194, 196, 198, 200, 202, 205, 208, 210, 212, 214, 216, 218, 220,
        221, 224, 226, 228, 230, 234, 236, 239, 240, 242, 244, 248, 252,
        254, 259, 264, 268, 272, 275, 280, 286, 291, 293, 294, 301, 318,
        330, 386, 552]),
 array([1252,    1,    1,    1,    1,    2,    2,    2,    1,    2,    3,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    2,    2,    1,    2,    1,    1,    1,    1,    6,    1,
           1,    2,    3,    1,    2,   15,    2,    2,    4,    5,    1,
           3,    3,   

In [79]:
np.unique(df['3SsnPorch'],return_counts = True)

(array([  0,  23,  96, 130, 140, 144, 153, 162, 168, 180, 182, 196, 216,
        238, 245, 290, 304, 320, 407, 508]),
 array([1436,    1,    1,    1,    1,    2,    1,    1,    3,    2,    1,
           1,    2,    1,    1,    1,    1,    1,    1,    1]))

In [80]:
np.unique(df['ScreenPorch'],return_counts = True)

(array([  0,  40,  53,  60,  63,  80,  90,  95,  99, 100, 116, 119, 120,
        122, 126, 128, 130, 140, 142, 143, 144, 145, 147, 152, 153, 154,
        155, 156, 160, 161, 163, 165, 168, 170, 175, 176, 178, 180, 182,
        184, 185, 189, 190, 192, 197, 198, 200, 204, 210, 216, 220, 222,
        224, 225, 233, 234, 252, 259, 260, 263, 265, 266, 271, 273, 276,
        287, 288, 291, 312, 322, 374, 385, 396, 410, 440, 480]),
 array([1344,    1,    1,    1,    1,    1,    3,    1,    1,    2,    1,
           1,    5,    1,    3,    1,    1,    1,    2,    1,    3,    1,
           3,    1,    1,    1,    1,    1,    3,    1,    1,    1,    3,
           2,    1,    2,    1,    4,    1,    2,    1,    4,    1,    6,
           1,    2,    2,    1,    1,    2,    1,    1,    5,    1,    1,
           1,    1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
           2,    1,    1,    1,    1,    1,    1,    1,    1,    1]))

In [81]:
np.unique(df['PoolArea'],return_counts = True)

(array([  0, 480, 512, 519, 555, 576, 648, 738]),
 array([1453,    1,    1,    1,    1,    1,    1,    1]))

In [82]:
np.unique(df['PoolQC'],return_counts = True)

(array(['0', 'Ex', 'Fa', 'Gd'], dtype=object), array([1453,    2,    2,    3]))

In [83]:
np.unique(df['Fence'],return_counts = True)

(array(['0', 'GdPrv', 'GdWo', 'MnPrv', 'MnWw'], dtype=object),
 array([1179,   59,   54,  157,   11]))

In [84]:
np.unique(df['MiscFeature'],return_counts = True)

(array(['0', 'Gar2', 'Othr', 'Shed', 'TenC'], dtype=object),
 array([1406,    2,    2,   49,    1]))

In [85]:
np.unique(df['MiscVal'],return_counts = True)

(array([    0,    54,   350,   400,   450,   480,   500,   560,   600,
          620,   700,   800,  1150,  1200,  1300,  1400,  2000,  2500,
         3500,  8300, 15500]),
 array([1408,    1,    1,   11,    4,    2,    8,    1,    4,    1,    5,
           1,    1,    2,    1,    1,    4,    1,    1,    1,    1]))

In [86]:
np.unique(df['MoSold'],return_counts = True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 58,  52, 106, 141, 204, 253, 234, 122,  63,  89,  79,  59]))

In [87]:
np.unique(df['YrSold'],return_counts = True)

(array([2006, 2007, 2008, 2009, 2010]), array([314, 329, 304, 338, 175]))

In [88]:
np.unique(df['SaleType'],return_counts = True)

(array(['COD', 'CWD', 'Con', 'ConLD', 'ConLI', 'ConLw', 'New', 'Oth', 'WD'],
       dtype=object),
 array([  43,    4,    2,    9,    5,    5,  122,    3, 1267]))

In [89]:
np.unique(df['SaleCondition'],return_counts = True)

(array(['Abnorml', 'AdjLand', 'Alloca', 'Family', 'Normal', 'Partial'],
       dtype=object),
 array([ 101,    4,   12,   20, 1198,  125]))

In [90]:
np.unique(df['SalePrice'],return_counts = True)

(array([ 34900,  35311,  37900,  39300,  40000,  52000,  52500,  55000,
         55993,  58500,  60000,  61000,  62383,  64500,  66500,  67000,
         68400,  68500,  72500,  73000,  75000,  75500,  76000,  76500,
         78000,  79000,  79500,  79900,  80000,  80500,  81000,  82000,
         82500,  83000,  83500,  84000,  84500,  84900,  85000,  85400,
         85500,  86000,  87000,  87500,  88000,  89000,  89471,  89500,
         90000,  90350,  91000,  91300,  91500,  92000,  92900,  93000,
         93500,  94000,  94500,  94750,  95000,  96500,  97000,  97500,
         98000,  98300,  98600,  99500,  99900, 100000, 101000, 101800,
        102000, 102776, 103000, 103200, 103600, 104000, 104900, 105000,
        105500, 105900, 106000, 106250, 106500, 107000, 107400, 107500,
        107900, 108000, 108480, 108500, 108959, 109000, 109008, 109500,
        109900, 110000, 110500, 111000, 111250, 112000, 112500, 113000,
        114500, 114504, 115000, 116000, 116050, 116500, 116900, 